import '~/styles/globals.css';
import { ReactQueryWrapper } from './react-query-wrapper';
import { Navigation } from '~/components/navigation';
import { Footer } from '~/components/footer';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ReactQueryWrapper>
      <html lang="hu">
        <body className="grid min-h-screen grid-cols-1 grid-rows-[1fr_auto]">
          <div>
            <Navigation />
            {children}
          </div>

          <Footer />
        </body>
      </html>
    </ReactQueryWrapper>
  );
}
